name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.19]
        os: [windows-latest, ubuntu-latest]
        arch: [amd64, arm64, 386]
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}

    - name: Build for ${{ matrix.os }}-${{ matrix.arch }}
      run: GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} go build -v -o myapp_${{ matrix.os }}_${{ matrix.arch }}

    - name: Test
      run: go test -v ./...
