name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    outputs:
      binary: ${{ steps.build.outputs.binary }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.19

    - name: Build for Linux ARM64
      id: build
      run: |
        mkdir -p bin
        GOOS=linux GOARCH=arm64 go build -v -o bin/myapp_linux_arm64
        echo "::set-output name=binary::bin/myapp_linux_arm64"

    - name: Test
      run: go test -v ./...

    - name: Upload binary
      uses: actions/upload-artifact@v2
      with:
        name: myapp_linux_arm64
        path: ${{ steps.build.outputs.binary }}
